// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/pills.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicineName  string                 `protobuf:"bytes,1,opt,name=medicine_name,json=medicineName,proto3" json:"medicine_name,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_api_proto_pills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetMedicineName() string {
	if x != nil {
		return x.MedicineName
	}
	return ""
}

func (x *ScheduleRequest) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ScheduleRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ScheduleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ScheduleIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    int64                  `protobuf:"varint,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleIDResponse) Reset() {
	*x = ScheduleIDResponse{}
	mi := &file_api_proto_pills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleIDResponse) ProtoMessage() {}

func (x *ScheduleIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleIDResponse.ProtoReflect.Descriptor instead.
func (*ScheduleIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleIDResponse) GetScheduleId() int64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type ScheduleIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScheduleId    int64                  `protobuf:"varint,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleIDRequest) Reset() {
	*x = ScheduleIDRequest{}
	mi := &file_api_proto_pills_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleIDRequest) ProtoMessage() {}

func (x *ScheduleIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleIDRequest.ProtoReflect.Descriptor instead.
func (*ScheduleIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ScheduleIDRequest) GetScheduleId() int64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_api_proto_pills_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{3}
}

func (x *UserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MedicineName  string                 `protobuf:"bytes,2,opt,name=medicine_name,json=medicineName,proto3" json:"medicine_name,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TakingTime    []string               `protobuf:"bytes,6,rep,name=taking_time,json=takingTime,proto3" json:"taking_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_api_proto_pills_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScheduleResponse) GetMedicineName() string {
	if x != nil {
		return x.MedicineName
	}
	return ""
}

func (x *ScheduleResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ScheduleResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ScheduleResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ScheduleResponse) GetTakingTime() []string {
	if x != nil {
		return x.TakingTime
	}
	return nil
}

type ScheduleIDList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleIds   []int64                `protobuf:"varint,1,rep,packed,name=schedule_ids,json=scheduleIds,proto3" json:"schedule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleIDList) Reset() {
	*x = ScheduleIDList{}
	mi := &file_api_proto_pills_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleIDList) ProtoMessage() {}

func (x *ScheduleIDList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleIDList.ProtoReflect.Descriptor instead.
func (*ScheduleIDList) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleIDList) GetScheduleIds() []int64 {
	if x != nil {
		return x.ScheduleIds
	}
	return nil
}

type Taking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicineName  string                 `protobuf:"bytes,1,opt,name=medicine_name,json=medicineName,proto3" json:"medicine_name,omitempty"`
	TakingTime    string                 `protobuf:"bytes,2,opt,name=taking_time,json=takingTime,proto3" json:"taking_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taking) Reset() {
	*x = Taking{}
	mi := &file_api_proto_pills_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taking) ProtoMessage() {}

func (x *Taking) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taking.ProtoReflect.Descriptor instead.
func (*Taking) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{6}
}

func (x *Taking) GetMedicineName() string {
	if x != nil {
		return x.MedicineName
	}
	return ""
}

func (x *Taking) GetTakingTime() string {
	if x != nil {
		return x.TakingTime
	}
	return ""
}

type TakingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Takings       []*Taking              `protobuf:"bytes,1,rep,name=takings,proto3" json:"takings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakingList) Reset() {
	*x = TakingList{}
	mi := &file_api_proto_pills_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakingList) ProtoMessage() {}

func (x *TakingList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pills_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakingList.ProtoReflect.Descriptor instead.
func (*TakingList) Descriptor() ([]byte, []int) {
	return file_api_proto_pills_proto_rawDescGZIP(), []int{7}
}

func (x *TakingList) GetTakings() []*Taking {
	if x != nil {
		return x.Takings
	}
	return nil
}

var File_api_proto_pills_proto protoreflect.FileDescriptor

const file_api_proto_pills_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/pills.proto\x12\x03ptr\"\x89\x01\n" +
	"\x0fScheduleRequest\x12#\n" +
	"\rmedicine_name\x18\x01 \x01(\tR\fmedicineName\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"5\n" +
	"\x12ScheduleIDResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\x03R\n" +
	"scheduleId\"M\n" +
	"\x11ScheduleIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\x03R\n" +
	"scheduleId\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xbb\x01\n" +
	"\x10ScheduleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rmedicine_name\x18\x02 \x01(\tR\fmedicineName\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtaking_time\x18\x06 \x03(\tR\n" +
	"takingTime\"3\n" +
	"\x0eScheduleIDList\x12!\n" +
	"\fschedule_ids\x18\x01 \x03(\x03R\vscheduleIds\"N\n" +
	"\x06Taking\x12#\n" +
	"\rmedicine_name\x18\x01 \x01(\tR\fmedicineName\x12\x1f\n" +
	"\vtaking_time\x18\x02 \x01(\tR\n" +
	"takingTime\"3\n" +
	"\n" +
	"TakingList\x12%\n" +
	"\atakings\x18\x01 \x03(\v2\v.ptr.TakingR\atakings2\x86\x02\n" +
	"\n" +
	"PTRService\x12A\n" +
	"\x0eCreateSchedule\x12\x14.ptr.ScheduleRequest\x1a\x17.ptr.ScheduleIDResponse\"\x00\x12>\n" +
	"\vGetSchedule\x12\x16.ptr.ScheduleIDRequest\x1a\x15.ptr.ScheduleResponse\"\x00\x12<\n" +
	"\x0fGetSchedulesIDs\x12\x12.ptr.UserIDRequest\x1a\x13.ptr.ScheduleIDList\"\x00\x127\n" +
	"\x0eGetNextTakings\x12\x12.ptr.UserIDRequest\x1a\x0f.ptr.TakingList\"\x00B(Z&pills-taking-reminder/internal/grpc/pbb\x06proto3"

var (
	file_api_proto_pills_proto_rawDescOnce sync.Once
	file_api_proto_pills_proto_rawDescData []byte
)

func file_api_proto_pills_proto_rawDescGZIP() []byte {
	file_api_proto_pills_proto_rawDescOnce.Do(func() {
		file_api_proto_pills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pills_proto_rawDesc), len(file_api_proto_pills_proto_rawDesc)))
	})
	return file_api_proto_pills_proto_rawDescData
}

var file_api_proto_pills_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_pills_proto_goTypes = []any{
	(*ScheduleRequest)(nil),    // 0: ptr.ScheduleRequest
	(*ScheduleIDResponse)(nil), // 1: ptr.ScheduleIDResponse
	(*ScheduleIDRequest)(nil),  // 2: ptr.ScheduleIDRequest
	(*UserIDRequest)(nil),      // 3: ptr.UserIDRequest
	(*ScheduleResponse)(nil),   // 4: ptr.ScheduleResponse
	(*ScheduleIDList)(nil),     // 5: ptr.ScheduleIDList
	(*Taking)(nil),             // 6: ptr.Taking
	(*TakingList)(nil),         // 7: ptr.TakingList
}
var file_api_proto_pills_proto_depIdxs = []int32{
	6, // 0: ptr.TakingList.takings:type_name -> ptr.Taking
	0, // 1: ptr.PTRService.CreateSchedule:input_type -> ptr.ScheduleRequest
	2, // 2: ptr.PTRService.GetSchedule:input_type -> ptr.ScheduleIDRequest
	3, // 3: ptr.PTRService.GetSchedulesIDs:input_type -> ptr.UserIDRequest
	3, // 4: ptr.PTRService.GetNextTakings:input_type -> ptr.UserIDRequest
	1, // 5: ptr.PTRService.CreateSchedule:output_type -> ptr.ScheduleIDResponse
	4, // 6: ptr.PTRService.GetSchedule:output_type -> ptr.ScheduleResponse
	5, // 7: ptr.PTRService.GetSchedulesIDs:output_type -> ptr.ScheduleIDList
	7, // 8: ptr.PTRService.GetNextTakings:output_type -> ptr.TakingList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_pills_proto_init() }
func file_api_proto_pills_proto_init() {
	if File_api_proto_pills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pills_proto_rawDesc), len(file_api_proto_pills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pills_proto_goTypes,
		DependencyIndexes: file_api_proto_pills_proto_depIdxs,
		MessageInfos:      file_api_proto_pills_proto_msgTypes,
	}.Build()
	File_api_proto_pills_proto = out.File
	file_api_proto_pills_proto_goTypes = nil
	file_api_proto_pills_proto_depIdxs = nil
}
